spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: 127.0.0.1:8048
        namespace: 7dedf96c-a508-4c19-80dc-0b05a1d04d51
  #redis
  redis:
    database: 1
    host: localhost
    port: 6379
    password: