spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechat_mp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: wechat_mp
    password: wechat_mp
#mybatis
mybatis-plus:
  global-config:
    db-config:
      #主键类型
      id-type: auto
      #逻辑删除
      logic-delete-value: 0
      logic-not-delete-value: 1
  #xml位置
  mapper-locations: classpath*:mapper/**/*.xml
  #po位置
  type-aliases-package: com.cjh.wechatmp.po
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# xxl-job
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:7001/xxl-job-admin
    executor:
      ip: ''
      address: ''
      appname: xxl-job-executor-wechat-mp
      logpath: /home/logs/xxl-job/wechat-mp
      logretentiondays: 30
      port: 7102