spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: 127.0.0.1:8048
        namespace: 2b5a6fa4-6d1a-45b0-b4c0-65ddccad640a
  #redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: