spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: 127.0.0.1:8048
        namespace: d892e55a-3aea-4bcf-a642-77f2135cee97
  #redis
  redis:
    database: 1
    host: localhost
    port: 6379
    password: