spring:
  #redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
#openFeign
feign:
  client:
    config:
      #If you prefer using configuration properties to configured all @FeignClient, you can create configuration properties with default feign name.
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
  hystrix:
    enabled: true
#hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#feign client log
logging:
  level:
    com.cjh.wechatmp.feign: debug
    #上面自定义日志后，居然会影响nacos日志~
    com.alibaba.nacos.client.naming: warn

