spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: 127.0.0.1:8048
        namespace: 12b71695-5d94-4c96-86ca-cb906432bede
  #redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: