spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: yunibobo.cn
        namespace: 32d93268-bdb6-40a0-8740-a211f74b9a9f
  #redis
  redis:
    database: 0
    host: yunibobo.cn
    port: 16379
    password: myredis

