spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: 127.0.0.1:8048
        namespace: a8f9a937-cccb-4b91-a30e-fba77400cc32
  #redis
  redis:
    database: 1
    host: localhost
    port: 6379
    password: