spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: http://nacos.yunibobo.cn
        namespace: dbe63b4c-fa43-4eb0-ab4c-7b6f3cd71c79
  #redis
  redis:
    database: 2
    host: yunibobo.cn
    port: 16379
    password: myredis